version: "3.6"

services:
  db:
    env_file:
      - ".env"
    image: "postgres:9.6"
    volumes:
      - "db:/var/lib/postgresql/data"

  web:
    build: "."
    depends_on:
      - "db"
    env_file:
      - ".env"
    ports:
      - "4000:4000"
    volumes:
      - ".:/app"

volumes:
  db: {}